'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.34014
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FC2LiveCommentTalker2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  ぁぃ	(ﾟДﾟ)ﾉ ｧｨ	顔文字	
        '''あい	(　´∀｀)つ≡≡≡愛愛愛)Д｀)ｸﾞｼｬ	顔文字	
        '''あいごー	&lt;丶｀Д´&gt;ｱｲｺﾞｰ	顔文字	
        '''あいやー	(｀ハ´)ｱｲﾔｰ	顔文字	
        '''あいーん	(＿´Д｀) ｱｲｰﾝ	顔文字	
        '''あう	ヽ(´Д`；)ﾉｱｩ...	顔文字	
        '''あうあう	⊂ミ⊃＾ω＾ ）⊃　ｱｳｱｳ!!	顔文字	
        '''あうあうあー	(_Д_)ｱｳｱｳｱｰ	顔文字	
        '''あうあうあー	(^p^)あうあうあー	顔文字	
        '''あうと	⊂ミ⊃＾ω＾ ）⊃　ｱｳｱｳ!!	顔文字	
        '''あうー	( ﾟρﾟ )ｱｩｰ	顔文字	
        '''あきたよ	(　ﾟдﾟ)ｱｷﾀﾖ…	顔文字	
        '''あげ	(´∀｀∩)↑age↑	顔文字	
        '''あさぴー	(-@∀@)	顔文字	
        '''あさぴー	ヽ(-@∀@)ﾉ ﾃﾞｯﾁage	顔文字	
        '''あせ	(；´∀｀)	顔文字	
        '''あせ	(；・∀・)	顔文字	
        '''あせ	(；´Д｀)	顔文字	
        '''あせ	（；^ω^）	顔文字	
        '''あせ	:(；ﾞﾟ&apos;ωﾟ&apos;):	顔文字	
        '''あせ	(； ･`д･´)	顔文字	
        '''あたふた	ｱﾀヽ(д｀ヽ彡ノ´д)ノﾌﾀ	顔文字	
        '''あちゃー	(ﾉ∀`)ｱﾁｬｰ	顔文字	
        '''あちゃー [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property google_std() As String
            Get
                Return ResourceManager.GetString("google_std", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
